services:
  elasticsearch:
    image: ghcr.io/tal-sitton/seret-search:latest
    pull_policy: always
    ports:
      - 9200:9200

  kibana:
    image: kibana:8.13.0
    pull_policy: always
    ports:
      - 5601:5601

  proxy-vpn:
    image: ghcr.io/tal-sitton/proxy-vpn:latest
    pull_policy: always
    ports:
      - 8118:8118
    env_file:
      - .env
    privileged: true
    dns: 1.1.1.1