from .seret_movie_info_fetcher import SeretMovieInfoFetcher
from .elastic_seret_movie_info_fetcher import ElasticSeretMovieInfoFetcher
from .online_seret_movie_info_fetcher import OnlineSeretMovieInfoFetcher
from .composite import CompositeSeretMovieInfoFetcher
