# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: run program

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "32 6 * * *"

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      #      - name: cp chromium
      #        run: |
      #          sudo chmod -R 777 .github/workflows/chromium-browser
      #          sudo cp .github/workflows/chromium-browser /usr/bin/chromium-browser
      #          sudo chmod +x /usr/bin/chromium-browser
      #
      #      - name: Install dependencies
      #        run: |
      #          python -m pip install --upgrade pip
      #          pip install -r requirements.txt
      #
      #      - name: Run main.py
      #        run: |
      #          python main.py

      - name: update file and push to remote
        run: |
          echo "Test push commit to the remote in the workflow" >> test.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add "test.txt"
          git commit -m "Update test.txt" test.txt
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
